version: '3.8'

services: 
  postgres_db:
    image: postgres
    container_name: shop-postgres
    restart: always
    env_file:
    - .env
    ports:
      - "5436:5432"

  app:
    build: .
    container_name: shop-app
    restart: always
    ports:
      - "8009:8009"
    depends_on:
      - postgres_db

  nginx:
       image: nginx
       container_name: nginx
       ports:
         - "8010:80"
       volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro