click_house:
  host: localhost
  port: 9000
  db_name: "test_db"

postgres:
  host: "postgres_db"
  port: 5432
  db_name: "all_social_networks_shop"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379
  db_name: 1

http_server:
    port: "8009"
    read_timeout: 10s
    write_timeout: 10s
    max_header_bytes: 10

cache: 
  expiration: 60s

email_sender:
  from: "sixojke@outlook.com"
  password: "Dimas228"
  host: "smtp-mail.outlook.com"
  port: 587

payok:
  shop_id: 7128
  success_url: "https://t.me/cs2sma_bot"

service:
  users:
    auth:
      verification_code_length: 6
      jwt:
        access_token_ttl: 15m
        refresh_token_ttl: 14400m

handler:
  pagination:
    default_limit: 10
    max_limit: 100
  
