basePath: /api/v1
definitions:
  domain.Pagination:
    properties:
      data: {}
      limit:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  domain.User:
    properties:
      balance:
        type: number
      email:
        type: string
      id:
        type: integer
      last_visit_at:
        type: string
      password:
        type: string
      registered_at:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  v1.categoryCreateInp:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  v1.categoryEditInp:
    properties:
      change_img:
        type: boolean
      id:
        type: integer
      name:
        type: string
    required:
    - change_img
    - id
    - name
    type: object
  v1.dataResponse:
    properties:
      count:
        type: integer
      data: {}
    type: object
  v1.idResponse:
    properties:
      id: {}
    type: object
  v1.paginationResponse:
    properties:
      pagination:
        $ref: '#/definitions/domain.Pagination'
    type: object
  v1.refreshTokenInp:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  v1.response:
    properties:
      message:
        type: string
    type: object
  v1.subcategoryCreateInp:
    properties:
      category_id:
        type: integer
      min_hold_time:
        type: integer
      name:
        type: string
    required:
    - category_id
    - min_hold_time
    - name
    type: object
  v1.subcategoryEditInp:
    properties:
      id:
        type: integer
      min_hold_time:
        type: integer
      name:
        type: string
    required:
    - id
    - min_hold_time
    - name
    type: object
  v1.tokenResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  v1.userManagementBan:
    properties:
      ban_status:
        type: boolean
      id:
        type: integer
    required:
    - ban_status
    - id
    type: object
  v1.userSignInInp:
    properties:
      password:
        maxLength: 64
        minLength: 8
        type: string
      username:
        maxLength: 32
        minLength: 6
        type: string
    required:
    - password
    - username
    type: object
  v1.userSignUpInp:
    properties:
      email:
        maxLength: 64
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
      username:
        maxLength: 32
        minLength: 6
        type: string
    required:
    - email
    - password
    - username
    type: object
  v1.userVerifyInp:
    properties:
      code:
        type: string
      id:
        type: integer
    required:
    - code
    - id
    type: object
host: localhost:8009
info:
  contact: {}
  description: REST API for shop
  title: All social networks shop API
  version: "1.0"
paths:
  /admin/category/{id}:
    delete:
      consumes:
      - application/json
      description: delete category by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: Category Delete
      tags:
      - category
  /admin/category/create:
    post:
      consumes:
      - multipart/form-data
      description: create category
      parameters:
      - description: create category
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.categoryCreateInp'
      - description: Category image
        in: formData
        name: img
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.idResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: Category Create
      tags:
      - category
  /admin/category/edit:
    patch:
      consumes:
      - application/json
      description: edit category by id
      parameters:
      - description: edit category name, img
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.categoryEditInp'
      - description: Category image
        in: formData
        name: img
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: Category Edit
      tags:
      - category
  /admin/log:
    get:
      consumes:
      - application/json
      description: get logs with pagination
      parameters:
      - default: 10
        description: Number of items per page
        in: query
        maximum: 100
        name: limit
        type: integer
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Pagination'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: Logs with pagination
      tags:
      - log
  /admin/subcategory/{id}:
    delete:
      consumes:
      - application/json
      description: delete subcategory by id
      parameters:
      - description: subcategory id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: Subcategory Delete
      tags:
      - subcategory
  /admin/subcategory/create:
    post:
      consumes:
      - application/json
      description: create subcategory
      parameters:
      - description: create subcategory
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.subcategoryCreateInp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.idResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: Subcategory Create
      tags:
      - subcategory
  /admin/subcategory/edit:
    patch:
      consumes:
      - application/json
      description: edit subcategory by id
      parameters:
      - description: edit subcategory name, min hold time
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.subcategoryEditInp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: Subcategory Edit
      tags:
      - subcategory
  /admin/user-management/ban:
    patch:
      consumes:
      - application/json
      description: edit banned user
      parameters:
      - description: edit banned user
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.userManagementBan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: User edit banned
      tags:
      - user
  /categories:
    get:
      consumes:
      - application/json
      description: get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Get all categories
      tags:
      - categories
  /categories/{category_id}:
    get:
      consumes:
      - application/json
      description: get subcategories by category_id
      parameters:
      - description: category id
        in: path
        name: category_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Get subcategories
      tags:
      - subcategories
  /products:
    get:
      consumes:
      - application/json
      description: Get all products with pagination and filters
      parameters:
      - default: 10
        description: Number of items per page
        in: query
        maximum: 100
        name: limit
        type: integer
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - description: category_id
        in: query
        name: category_id
        type: integer
      - description: subcategory_id
        in: query
        name: subcategory_id
        type: integer
      - default: 0
        description: 'Product availability: enter 1 if true, 0 if false'
        in: query
        name: is_available
        type: integer
      - description: 'sort price: enter asc or desc'
        in: query
        name: sort_price
        type: string
      - description: 'sort defect: enter asc or desc'
        in: query
        name: sort_defect
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.paginationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Products with filters
      tags:
      - products
  /user:
    get:
      consumes:
      - application/json
      description: user get by refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - UsersAuth: []
      summary: User get by refresh token
      tags:
      - user
  /users/auth/refresh:
    post:
      consumes:
      - application/json
      description: user refresh tokens
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.refreshTokenInp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: User Refresh Tokens
      tags:
      - users-auth
  /users/sign-in:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.userSignInInp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: User SignIn
      tags:
      - users-auth
  /users/sign-up:
    post:
      consumes:
      - application/json
      description: create user account
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.userSignUpInp'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: User SignUp
      tags:
      - users-auth
  /users/verify/:
    post:
      consumes:
      - application/json
      description: user verify registration
      parameters:
      - description: user verify
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.userVerifyInp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: User Verify Registration
      tags:
      - users-auth
securityDefinitions:
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
